### ISSUE TITLE
ARM architecture is not supported

### ISSUE THREAD

**Issue by gosuto-inzasheru** [kservices/gBridge-docker#3]
`web` and `redis-worker` cannot run properly due to (what I think is) an unsupported architecture. This is after running `docker-compose up` on an RPi3 running Raspbian 9:
```
redis-worker_1  | standard_init_linux.go:207: exec user process caused "exec format error"
web_1           | standard_init_linux.go:207: exec user process caused "exec format error"
```
I was already able to circumvent a similar problem with the `mysql` image by running a mysql server locally instead of depending on a dockered database server. This might actually be the fastest solution for all these images.

I did find your comments on how to use the arm32v6 (although I think for the RPi3 it is again a different architecture??) but ran into this:
```
Pulling web (pkap/gbridge-web-arm32v6:latest)...
ERROR: pull access denied for pkap/gbridge-web-arm32v6, repository does not exist or may require 'docker login'
```
and
```
Pulling redis-worker (pkap/gbridge-redis-worker-arm32v6:latest)...
ERROR: pull access denied for pkap/gbridge-redis-worker-arm32v6, repository does not exist or may require 'docker login'
```
Anyway I still think the most efficient solution to all of this would be to expand a bit on your answer to [this issue here](https://github.com/kservices/gBridge/issues/3) and to cut out Docker dependancy completely. I think it is easier to get a web server, database and redis up and running and configured than to port all docker files to arm32v6/arm32v7/armhf! Or am I missing something?

**Comment by ivanovlk** [comment]
I think you are pulling wrong image...
It should be "pkap/gbridge-redis-worker:arm32v6-latest" 

The tag is: "arm32v6-latest" and the image "pkap/gbridge-redis-worker"

Same for Web-fpm : "pkap/gbridge-web-fpm:arm32v6-latest"

**Comment by ivanovlk** [comment]
Did that on Rpi3 few months ago and worked like a charm :)

**Comment by gosuto-inzasheru** [comment]
Can confirm that these are the right image names and that they work on Raspberry Pi 3:
- `pkap/gbridge-redis-worker:arm32v6-latest`
- `pkap/gbridge-web-fpm:arm32v6-latest`
